# Generated by Django 3.2 on 2021-07-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_alter_location_coordinates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address', 'coordinates')},
        ),
    ]
