# Generated by Django 3.2 on 2021-07-26 20:08

from django.db import migrations


def calculate_price(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    item_set = OrderItem.objects.all()
    for item in item_set.iterator():
        item.price = item.product.price * item.quantity
        item.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [("foodcartapp", "0042_orderitem_price")]

    operations = [migrations.RunPython(calculate_price)]
