# Generated by Django 3.2 on 2021-07-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
        ('foodcartapp', '0043_auto_20210726_2320'),
    ]

    operations = [
    ]
