# Generated by Django 3.2 on 2021-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_merge_0042_orderitem_price_0043_auto_20210726_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Processing', 'В работе'), ('Delivered', 'Доставка'), ('Cancelled', 'Отменён'), ('Completed', 'Выполнен')], default='New', max_length=10),
        ),
    ]
